name: ascii_flow

on: push 

jobs:
    ASCII-Workflow:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: List Repo Files
          run: ls -ltra
        - name: Execute Shell Scrip
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh