name: First-WorkFlow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v7

        - name: List and Read Files
          run: | 
           echo "My first Github action message"
           ls -ltar
           cat README.md
        - name: Generate ASCII Content 
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWAR" >> dragon.txt

            