name: First-WorkFlow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My first Github action message"
        
        - name: List files
          run: ls 
        
        - name: Read file
          run: cat README.md

            