 name: docker-build-deploy

 on:
  workflow_dispatch:
     inputs:
       logLevel:
          description: 'Log Level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug

 env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: nginx
##Jobs can be defined at the 
##1.Workflow Level 
##2.JOB level
##3.Step level
 jobs:
    Docker-Build-Job:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

        - name: Docker Login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD}}
        
        - name: Docker publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.DOCKER_PASSWORD }}
    Docker-Deploy-Job:
        needs: Docker-Build-Job
        runs-on: ubuntu-latest
        concurrency:
          group: tesing the concurrency
          cancel-in-progress: false
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        - name: sleep command
          run: sleep 600

